### ISSUE TITLE
Language Server

### ISSUE THREAD

**Issue by jfreymuth** [aDotInTheVoid/hare-highlighing-vscode#3]
I'm currently working on a language server at [https://git.sr.ht/~jfreymuth/hare-ls](https://git.sr.ht/~jfreymuth/hare-ls).
It is at a point where it may be useful to people (mainly some autocompletion)

If anyone knows how to properly integrate this into an extension, help would be appreciated.

![screenshot](https://user-images.githubusercontent.com/13929369/184299693-7afb1566-bb70-4003-8ee8-8a27e6e4b5ee.png)

**Comment by jfreymuth** [comment]
I've pushed very basic language server support to https://github.com/jfreymuth/hare-highlighing-vscode/tree/language-server for testing

**Comment by aDotInTheVoid** [comment]
I don't think I wan't to integrate a lsp into this extention. It's so much larger and more complex that it really should be it's own thing. I'll keep this syntax highlighing only, and if you should publish your own extention for LSP (which may take code from this repo)

Sorry for taking so long to look at this
